name = "StochasticDelayDiffEq"
uuid = "29a0d76e-afc8-11e9-03a4-eda52ae4b960"
authors = ["Henrik Sykora <henrik1991@gmail.com>"]
version = "1.8.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
FastPower = "a4df4552-cc26-4903-aec0-212e50a0e84b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
DataStructures = "0.18"
DelayDiffEq = "5.28.3"
DiffEqBase = "6.122"
DiffEqNoiseProcess = "5"
FastPower = "1"
LinearAlgebra = "1.9"
Logging = "1.9"
Random = "1.9"
RandomNumbers = "1"
RecursiveArrayTools = "1,2,3"
Reexport = "1.0"
SciMLBase = "2.59.2"
SparseArrays = "1.9"
StaticArrays = "1.0"
StochasticDiffEq = "6.72.1"
UnPack = "0.1, 1.0"
julia = "1.9"

[extras]
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DiffEqDevTools", "Test", "SafeTestsets"]
